/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lab1mongo;

import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author sergi
 */
public class Interfaz_Principal extends javax.swing.JFrame {

    /**
     * Creates new form Interfaz_Principal
     */
    
    Conexion consulta = new Conexion();
    String cons, cons0, cons1, cons2, cons3;
    public Interfaz_Principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        InterfazCRUD = new javax.swing.JFrame();
        btnPelicula = new javax.swing.JButton();
        btnProductora = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        Interfaz_Consulta = new javax.swing.JFrame();
        consProd2 = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        consTitulo = new javax.swing.JButton();
        consFranquicia = new javax.swing.JButton();
        consRango = new javax.swing.JButton();
        consProd1 = new javax.swing.JButton();
        ConsultaPorFranquicia = new javax.swing.JFrame();
        jLabel3 = new javax.swing.JLabel();
        txtFranquicia = new javax.swing.JTextField();
        btnConsulta = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtConsulta = new javax.swing.JTextPane();
        btnBack1 = new javax.swing.JButton();
        ConsultaPorRango = new javax.swing.JFrame();
        btnConsulta1 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtConsulta1 = new javax.swing.JTextPane();
        jLabel4 = new javax.swing.JLabel();
        txtAño1 = new javax.swing.JTextField();
        txtAño2 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        btnBack2 = new javax.swing.JButton();
        ConsultaPorTitulo = new javax.swing.JFrame();
        txtTitulo = new javax.swing.JTextField();
        btnConsultar = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtConsulta2 = new javax.swing.JTextPane();
        lblTitulo = new javax.swing.JLabel();
        btnBack3 = new javax.swing.JButton();
        ConsultaProductora1 = new javax.swing.JFrame();
        txtProductora = new javax.swing.JTextField();
        jScrollPane4 = new javax.swing.JScrollPane();
        txtConsulta3 = new javax.swing.JTextPane();
        btnConsulta2 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        btnBack4 = new javax.swing.JButton();
        ConsultaProductora2 = new javax.swing.JFrame();
        txtProductora1 = new javax.swing.JTextField();
        jScrollPane5 = new javax.swing.JScrollPane();
        txtConsulta4 = new javax.swing.JTextPane();
        btnConsulta3 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        btnBack5 = new javax.swing.JButton();
        CRUDPelicula = new javax.swing.JFrame();
        btnCreatePeli = new javax.swing.JButton();
        btnReadPeli = new javax.swing.JButton();
        btnUpdatePeli = new javax.swing.JButton();
        btnDeletePeli = new javax.swing.JButton();
        jScrollPane7 = new javax.swing.JScrollPane();
        txtResultadoPeli = new javax.swing.JTextPane();
        txtIDPeli = new javax.swing.JTextField();
        txtNombrePeli = new javax.swing.JTextField();
        txtGeneroPeli = new javax.swing.JTextField();
        txtDirectorPeli = new javax.swing.JTextField();
        txtFranquiciaPeli = new javax.swing.JTextField();
        txtPaisPeli = new javax.swing.JTextField();
        txtAñoPeli = new javax.swing.JTextField();
        txtDuracionPeli = new javax.swing.JTextField();
        txtProductoraPeli = new javax.swing.JTextField();
        txtActor1 = new javax.swing.JTextField();
        txtActor2 = new javax.swing.JTextField();
        txtActor3 = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        btnBackCRUD2 = new javax.swing.JButton();
        CRUDProductora = new javax.swing.JFrame();
        btnCreateProd = new javax.swing.JButton();
        btnReadProd = new javax.swing.JButton();
        btnUpdateProd = new javax.swing.JButton();
        btnDeleteProd = new javax.swing.JButton();
        jScrollPane6 = new javax.swing.JScrollPane();
        txtResultadoProd = new javax.swing.JTextPane();
        txtID = new javax.swing.JTextField();
        txtNombreProd = new javax.swing.JTextField();
        txtAñoProd = new javax.swing.JTextField();
        txtWWW = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        btnBackCRUD = new javax.swing.JButton();
        btnCRUD = new javax.swing.JButton();
        btnConsultas = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        InterfazCRUD.setMinimumSize(new java.awt.Dimension(600, 600));

        btnPelicula.setText("Película");
        btnPelicula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPeliculaActionPerformed(evt);
            }
        });

        btnProductora.setText("Productora");
        btnProductora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProductoraActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel9.setText("CRUD");

        javax.swing.GroupLayout InterfazCRUDLayout = new javax.swing.GroupLayout(InterfazCRUD.getContentPane());
        InterfazCRUD.getContentPane().setLayout(InterfazCRUDLayout);
        InterfazCRUDLayout.setHorizontalGroup(
            InterfazCRUDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, InterfazCRUDLayout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(btnPelicula)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 83, Short.MAX_VALUE)
                .addComponent(btnProductora)
                .addGap(91, 91, 91))
            .addGroup(InterfazCRUDLayout.createSequentialGroup()
                .addGap(137, 137, 137)
                .addComponent(jLabel9)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        InterfazCRUDLayout.setVerticalGroup(
            InterfazCRUDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(InterfazCRUDLayout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(jLabel9)
                .addGap(62, 62, 62)
                .addGroup(InterfazCRUDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnProductora)
                    .addComponent(btnPelicula))
                .addContainerGap(117, Short.MAX_VALUE))
        );

        Interfaz_Consulta.setMinimumSize(new java.awt.Dimension(600, 600));

        consProd2.setText("Consulta Productora 2");
        consProd2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consProd2ActionPerformed(evt);
            }
        });

        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel2.setText("Consultas");

        consTitulo.setText("Consulta por Título");
        consTitulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consTituloActionPerformed(evt);
            }
        });

        consFranquicia.setText("Consulta por franquicia");
        consFranquicia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consFranquiciaActionPerformed(evt);
            }
        });

        consRango.setText("Consulta por rango de años");
        consRango.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consRangoActionPerformed(evt);
            }
        });

        consProd1.setText("Consulta Productora 1");
        consProd1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consProd1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Interfaz_ConsultaLayout = new javax.swing.GroupLayout(Interfaz_Consulta.getContentPane());
        Interfaz_Consulta.getContentPane().setLayout(Interfaz_ConsultaLayout);
        Interfaz_ConsultaLayout.setHorizontalGroup(
            Interfaz_ConsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Interfaz_ConsultaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnBack)
                .addGap(22, 22, 22))
            .addGroup(Interfaz_ConsultaLayout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addGroup(Interfaz_ConsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addGroup(Interfaz_ConsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(consRango, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(consTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(consFranquicia, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(consProd1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(consProd2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(155, Short.MAX_VALUE))
        );
        Interfaz_ConsultaLayout.setVerticalGroup(
            Interfaz_ConsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Interfaz_ConsultaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(28, 28, 28)
                .addComponent(consTitulo)
                .addGap(18, 18, 18)
                .addComponent(consFranquicia)
                .addGap(18, 18, 18)
                .addComponent(consRango)
                .addGap(18, 18, 18)
                .addComponent(consProd1)
                .addGap(18, 18, 18)
                .addComponent(consProd2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnBack)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        ConsultaPorFranquicia.setMinimumSize(new java.awt.Dimension(600, 600));

        jLabel3.setText("Nombre de la Franquicia:");

        btnConsulta.setText("Consultar");
        btnConsulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultaActionPerformed(evt);
            }
        });

        jScrollPane1.setViewportView(txtConsulta);

        btnBack1.setText("Back");
        btnBack1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBack1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ConsultaPorFranquiciaLayout = new javax.swing.GroupLayout(ConsultaPorFranquicia.getContentPane());
        ConsultaPorFranquicia.getContentPane().setLayout(ConsultaPorFranquiciaLayout);
        ConsultaPorFranquiciaLayout.setHorizontalGroup(
            ConsultaPorFranquiciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ConsultaPorFranquiciaLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(ConsultaPorFranquiciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1)
                    .addGroup(ConsultaPorFranquiciaLayout.createSequentialGroup()
                        .addComponent(btnConsulta)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnBack1))
                    .addGroup(ConsultaPorFranquiciaLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(txtFranquicia, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(36, Short.MAX_VALUE))
        );
        ConsultaPorFranquiciaLayout.setVerticalGroup(
            ConsultaPorFranquiciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ConsultaPorFranquiciaLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(ConsultaPorFranquiciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtFranquicia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ConsultaPorFranquiciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnConsulta)
                    .addComponent(btnBack1))
                .addGap(27, 27, 27)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(46, Short.MAX_VALUE))
        );

        ConsultaPorRango.setMinimumSize(new java.awt.Dimension(600, 600));

        btnConsulta1.setText("Consulta");
        btnConsulta1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsulta1ActionPerformed(evt);
            }
        });

        jScrollPane2.setViewportView(txtConsulta1);

        jLabel4.setText("Consulta de rango por años");

        jLabel5.setText("Año 1");

        jLabel6.setText("Año 2");

        btnBack2.setText("Back");
        btnBack2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBack2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ConsultaPorRangoLayout = new javax.swing.GroupLayout(ConsultaPorRango.getContentPane());
        ConsultaPorRango.getContentPane().setLayout(ConsultaPorRangoLayout);
        ConsultaPorRangoLayout.setHorizontalGroup(
            ConsultaPorRangoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ConsultaPorRangoLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(ConsultaPorRangoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2)
                    .addComponent(jLabel4)
                    .addGroup(ConsultaPorRangoLayout.createSequentialGroup()
                        .addGroup(ConsultaPorRangoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addGap(29, 29, 29)
                        .addGroup(ConsultaPorRangoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtAño1, javax.swing.GroupLayout.DEFAULT_SIZE, 147, Short.MAX_VALUE)
                            .addComponent(txtAño2))
                        .addGap(18, 18, 18)
                        .addGroup(ConsultaPorRangoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnConsulta1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnBack2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(60, Short.MAX_VALUE))
        );
        ConsultaPorRangoLayout.setVerticalGroup(
            ConsultaPorRangoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ConsultaPorRangoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addGroup(ConsultaPorRangoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtAño1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(btnConsulta1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(ConsultaPorRangoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtAño2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(btnBack2))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 159, Short.MAX_VALUE)
                .addContainerGap())
        );

        ConsultaPorTitulo.setMinimumSize(new java.awt.Dimension(600, 600));

        btnConsultar.setText("Consultar");
        btnConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarActionPerformed(evt);
            }
        });

        jScrollPane3.setViewportView(txtConsulta2);

        lblTitulo.setText("Título de la película:");

        btnBack3.setText("Back");
        btnBack3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBack3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ConsultaPorTituloLayout = new javax.swing.GroupLayout(ConsultaPorTitulo.getContentPane());
        ConsultaPorTitulo.getContentPane().setLayout(ConsultaPorTituloLayout);
        ConsultaPorTituloLayout.setHorizontalGroup(
            ConsultaPorTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ConsultaPorTituloLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(ConsultaPorTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(ConsultaPorTituloLayout.createSequentialGroup()
                        .addComponent(lblTitulo)
                        .addGap(18, 18, 18)
                        .addComponent(txtTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(ConsultaPorTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnConsultar)
                    .addComponent(btnBack3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        ConsultaPorTituloLayout.setVerticalGroup(
            ConsultaPorTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ConsultaPorTituloLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(ConsultaPorTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTitulo)
                    .addComponent(txtTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnConsultar))
                .addGap(18, 18, 18)
                .addGroup(ConsultaPorTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBack3))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        ConsultaProductora1.setMinimumSize(new java.awt.Dimension(600, 600));

        jScrollPane4.setViewportView(txtConsulta3);

        btnConsulta2.setText("Consultar");
        btnConsulta2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsulta2ActionPerformed(evt);
            }
        });

        jLabel7.setText("Productora:");

        btnBack4.setText("Back");
        btnBack4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBack4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ConsultaProductora1Layout = new javax.swing.GroupLayout(ConsultaProductora1.getContentPane());
        ConsultaProductora1.getContentPane().setLayout(ConsultaProductora1Layout);
        ConsultaProductora1Layout.setHorizontalGroup(
            ConsultaProductora1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ConsultaProductora1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(ConsultaProductora1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ConsultaProductora1Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(18, 18, 18)
                        .addComponent(txtProductora, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(ConsultaProductora1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, ConsultaProductora1Layout.createSequentialGroup()
                            .addComponent(btnConsulta2)
                            .addGap(173, 173, 173)
                            .addComponent(btnBack4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 347, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(31, Short.MAX_VALUE))
        );
        ConsultaProductora1Layout.setVerticalGroup(
            ConsultaProductora1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ConsultaProductora1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(ConsultaProductora1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtProductora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ConsultaProductora1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnConsulta2)
                    .addComponent(btnBack4))
                .addGap(11, 11, 11)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        ConsultaProductora2.setMinimumSize(new java.awt.Dimension(600, 600));

        jScrollPane5.setViewportView(txtConsulta4);

        btnConsulta3.setText("Consultar");
        btnConsulta3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsulta3ActionPerformed(evt);
            }
        });

        jLabel8.setText("Nombre de la productora:");

        btnBack5.setText("Back");
        btnBack5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBack5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ConsultaProductora2Layout = new javax.swing.GroupLayout(ConsultaProductora2.getContentPane());
        ConsultaProductora2.getContentPane().setLayout(ConsultaProductora2Layout);
        ConsultaProductora2Layout.setHorizontalGroup(
            ConsultaProductora2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ConsultaProductora2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(ConsultaProductora2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(ConsultaProductora2Layout.createSequentialGroup()
                        .addComponent(btnConsulta3)
                        .addGap(181, 181, 181)
                        .addComponent(btnBack5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 355, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(ConsultaProductora2Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(18, 18, 18)
                        .addComponent(txtProductora1)))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        ConsultaProductora2Layout.setVerticalGroup(
            ConsultaProductora2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ConsultaProductora2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ConsultaProductora2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtProductora1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(ConsultaProductora2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ConsultaProductora2Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(btnConsulta3))
                    .addGroup(ConsultaProductora2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnBack5)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 196, Short.MAX_VALUE)
                .addContainerGap())
        );

        CRUDPelicula.setMinimumSize(new java.awt.Dimension(600, 600));

        btnCreatePeli.setText("Create");
        btnCreatePeli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreatePeliActionPerformed(evt);
            }
        });

        btnReadPeli.setText("Read");
        btnReadPeli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReadPeliActionPerformed(evt);
            }
        });

        btnUpdatePeli.setText("Update");
        btnUpdatePeli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdatePeliActionPerformed(evt);
            }
        });

        btnDeletePeli.setText("Delete");
        btnDeletePeli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeletePeliActionPerformed(evt);
            }
        });

        jScrollPane7.setViewportView(txtResultadoPeli);

        jLabel14.setText("ID Pelicula");

        jLabel15.setText("Nombre Pelicula");

        jLabel16.setText("Genero");

        jLabel17.setText("Director");

        jLabel18.setText("Franquicia");

        jLabel19.setText("Pais de produccion");

        jLabel20.setText("Año de estreno");

        jLabel21.setText("Duración");

        jLabel22.setText("Productora");

        jLabel23.setText("Actor 1");

        jLabel24.setText("Actor 2");

        jLabel25.setText("Actor 3");

        btnBackCRUD2.setText("Back");
        btnBackCRUD2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackCRUD2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout CRUDPeliculaLayout = new javax.swing.GroupLayout(CRUDPelicula.getContentPane());
        CRUDPelicula.getContentPane().setLayout(CRUDPeliculaLayout);
        CRUDPeliculaLayout.setHorizontalGroup(
            CRUDPeliculaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CRUDPeliculaLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(CRUDPeliculaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(CRUDPeliculaLayout.createSequentialGroup()
                        .addComponent(jLabel19)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtPaisPeli))
                    .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(CRUDPeliculaLayout.createSequentialGroup()
                        .addGap(0, 10, Short.MAX_VALUE)
                        .addComponent(btnCreatePeli)
                        .addGap(18, 18, 18)
                        .addComponent(btnReadPeli)
                        .addGap(12, 12, 12)
                        .addComponent(btnUpdatePeli)
                        .addGap(18, 18, 18)
                        .addComponent(btnDeletePeli))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CRUDPeliculaLayout.createSequentialGroup()
                        .addGroup(CRUDPeliculaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel14)
                            .addComponent(jLabel15)
                            .addComponent(jLabel16)
                            .addComponent(jLabel17)
                            .addComponent(jLabel18))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(CRUDPeliculaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtFranquiciaPeli, javax.swing.GroupLayout.DEFAULT_SIZE, 233, Short.MAX_VALUE)
                            .addComponent(txtDirectorPeli)
                            .addComponent(txtGeneroPeli)
                            .addComponent(txtNombrePeli)
                            .addComponent(txtIDPeli)))
                    .addGroup(CRUDPeliculaLayout.createSequentialGroup()
                        .addGroup(CRUDPeliculaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel20)
                            .addComponent(jLabel21))
                        .addGap(18, 18, 18)
                        .addGroup(CRUDPeliculaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtDuracionPeli)
                            .addComponent(txtAñoPeli)))
                    .addGroup(CRUDPeliculaLayout.createSequentialGroup()
                        .addGroup(CRUDPeliculaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(CRUDPeliculaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel23)
                                .addComponent(jLabel24)
                                .addComponent(jLabel25))
                            .addComponent(jLabel22))
                        .addGap(12, 12, 12)
                        .addGroup(CRUDPeliculaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtProductoraPeli)
                            .addComponent(txtActor1)
                            .addComponent(txtActor2)
                            .addComponent(txtActor3))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                .addComponent(btnBackCRUD2)
                .addGap(24, 24, 24))
        );
        CRUDPeliculaLayout.setVerticalGroup(
            CRUDPeliculaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CRUDPeliculaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(CRUDPeliculaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtIDPeli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14)
                    .addComponent(btnBackCRUD2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(CRUDPeliculaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNombrePeli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(CRUDPeliculaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtGeneroPeli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(CRUDPeliculaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDirectorPeli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(CRUDPeliculaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtFranquiciaPeli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(CRUDPeliculaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPaisPeli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(CRUDPeliculaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtAñoPeli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel20))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(CRUDPeliculaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDuracionPeli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel21))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(CRUDPeliculaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtProductoraPeli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel22))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(CRUDPeliculaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtActor1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel23))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(CRUDPeliculaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtActor2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel24))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(CRUDPeliculaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtActor3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel25))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addGroup(CRUDPeliculaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCreatePeli)
                    .addComponent(btnReadPeli)
                    .addComponent(btnUpdatePeli)
                    .addComponent(btnDeletePeli))
                .addGap(28, 28, 28)
                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        CRUDProductora.setMinimumSize(new java.awt.Dimension(600, 600));

        btnCreateProd.setText("Create");
        btnCreateProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateProdActionPerformed(evt);
            }
        });

        btnReadProd.setText("Read");
        btnReadProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReadProdActionPerformed(evt);
            }
        });

        btnUpdateProd.setText("Update");
        btnUpdateProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateProdActionPerformed(evt);
            }
        });

        btnDeleteProd.setText("Delete");
        btnDeleteProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteProdActionPerformed(evt);
            }
        });

        jScrollPane6.setViewportView(txtResultadoProd);

        jLabel10.setText("ID");

        jLabel11.setText("Nombre");

        jLabel12.setText("Año de fundación");

        jLabel13.setText("Página Web");

        btnBackCRUD.setText("Back");
        btnBackCRUD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackCRUDActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout CRUDProductoraLayout = new javax.swing.GroupLayout(CRUDProductora.getContentPane());
        CRUDProductora.getContentPane().setLayout(CRUDProductoraLayout);
        CRUDProductoraLayout.setHorizontalGroup(
            CRUDProductoraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CRUDProductoraLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(CRUDProductoraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(CRUDProductoraLayout.createSequentialGroup()
                        .addComponent(btnCreateProd)
                        .addGap(18, 18, 18)
                        .addComponent(btnReadProd)
                        .addGap(12, 12, 12)
                        .addComponent(btnUpdateProd)
                        .addGap(18, 18, 18)
                        .addComponent(btnDeleteProd))
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(CRUDProductoraLayout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addGroup(CRUDProductoraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(CRUDProductoraLayout.createSequentialGroup()
                                .addComponent(jLabel13)
                                .addGap(18, 18, 18)
                                .addComponent(txtWWW))
                            .addGroup(CRUDProductoraLayout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtAñoProd))
                            .addGroup(CRUDProductoraLayout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addGap(18, 18, 18)
                                .addComponent(txtNombreProd))
                            .addGroup(CRUDProductoraLayout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addGap(18, 18, 18)
                                .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnBackCRUD)))
                .addContainerGap(33, Short.MAX_VALUE))
        );
        CRUDProductoraLayout.setVerticalGroup(
            CRUDProductoraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CRUDProductoraLayout.createSequentialGroup()
                .addContainerGap(23, Short.MAX_VALUE)
                .addGroup(CRUDProductoraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CRUDProductoraLayout.createSequentialGroup()
                        .addGroup(CRUDProductoraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10)
                            .addComponent(btnBackCRUD))
                        .addGap(18, 18, 18)
                        .addGroup(CRUDProductoraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtNombreProd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11))
                        .addGap(18, 18, 18)
                        .addComponent(txtAñoProd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(18, 18, 18)
                .addGroup(CRUDProductoraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtWWW, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(CRUDProductoraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCreateProd)
                    .addComponent(btnReadProd)
                    .addComponent(btnUpdateProd)
                    .addComponent(btnDeleteProd))
                .addGap(28, 28, 28)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnCRUD.setText("CRUD");
        btnCRUD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCRUDActionPerformed(evt);
            }
        });

        btnConsultas.setText("Consultas");
        btnConsultas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultasActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("Laboratorio Mongo ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(btnCRUD)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnConsultas)
                .addGap(77, 77, 77))
            .addGroup(layout.createSequentialGroup()
                .addGap(94, 94, 94)
                .addComponent(jLabel1)
                .addContainerGap(98, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(jLabel1)
                .addGap(69, 69, 69)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCRUD)
                    .addComponent(btnConsultas))
                .addContainerGap(129, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCRUDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCRUDActionPerformed
        // TODO add your handling code here:
        InterfazCRUD.setVisible(true);
        this.hide();
    }//GEN-LAST:event_btnCRUDActionPerformed

    private void btnConsultasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultasActionPerformed
        Interfaz_Consulta.setVisible(true);        
        this.hide();
    }//GEN-LAST:event_btnConsultasActionPerformed

    private void consProd2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consProd2ActionPerformed
        ConsultaProductora2.setVisible(true);
        Interfaz_Consulta.hide();
    }//GEN-LAST:event_consProd2ActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        
        //Interfaz_Principal.setVisible(true);
        //Interfaz_Consulta.hide();
    }//GEN-LAST:event_btnBackActionPerformed

    private void consTituloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consTituloActionPerformed
        ConsultaPorTitulo.setVisible(true);
        Interfaz_Consulta.hide();
    }//GEN-LAST:event_consTituloActionPerformed

    private void consFranquiciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consFranquiciaActionPerformed
        ConsultaPorFranquicia.setVisible(true);
        Interfaz_Consulta.hide();
    }//GEN-LAST:event_consFranquiciaActionPerformed

    private void consRangoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consRangoActionPerformed
        ConsultaPorRango.setVisible(true);
        Interfaz_Consulta.hide();
    }//GEN-LAST:event_consRangoActionPerformed

    private void consProd1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consProd1ActionPerformed
        ConsultaProductora1.setVisible(true);
        Interfaz_Consulta.hide();
    }//GEN-LAST:event_consProd1ActionPerformed

    private void btnConsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultaActionPerformed
        cons = consulta.consultaPorFranquicia(txtFranquicia.getText());
        txtConsulta.setText(cons);
    }//GEN-LAST:event_btnConsultaActionPerformed

    private void btnConsulta1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsulta1ActionPerformed
        int año1 = Integer.parseInt(txtAño1.getText());
        int año2 = Integer.parseInt(txtAño2.getText());
        cons = consulta.consultaPorRangoAño(año1,año2);
        txtConsulta1.setText(cons);
    }//GEN-LAST:event_btnConsulta1ActionPerformed

    private void btnConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarActionPerformed
        cons = consulta.consultaPorTituloPelicula(txtTitulo.getText());
        txtConsulta2.setText(cons);
    }//GEN-LAST:event_btnConsultarActionPerformed

    private void btnConsulta2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsulta2ActionPerformed
        cons = consulta.consultasProductora1(txtProductora.getText());
        txtConsulta3.setText(cons);
    }//GEN-LAST:event_btnConsulta2ActionPerformed

    private void btnConsulta3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsulta3ActionPerformed
        cons0 = consulta.cantidadPeliculas(txtProductora1.getText());
        cons1 = consulta.peliculaMenorDuracion(txtProductora1.getText());
        cons2 = consulta.peliculaMayorDuracion(txtProductora1.getText());
        cons3 = consulta.peliculaDuracionPromedio(txtProductora1.getText());
        txtConsulta4.setText(cons0 + cons1 + cons2 + cons3);
    }//GEN-LAST:event_btnConsulta3ActionPerformed

    private void btnBack1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBack1ActionPerformed
        Interfaz_Consulta.setVisible(true);
        ConsultaPorFranquicia.hide();
    }//GEN-LAST:event_btnBack1ActionPerformed

    private void btnBack2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBack2ActionPerformed
        Interfaz_Consulta.setVisible(true);
        ConsultaPorRango.hide();
    }//GEN-LAST:event_btnBack2ActionPerformed

    private void btnBack3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBack3ActionPerformed
        Interfaz_Consulta.setVisible(true);
        ConsultaPorTitulo.hide();
    }//GEN-LAST:event_btnBack3ActionPerformed

    private void btnBack4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBack4ActionPerformed
        Interfaz_Consulta.setVisible(true);
        ConsultaProductora1.hide();
    }//GEN-LAST:event_btnBack4ActionPerformed

    private void btnBack5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBack5ActionPerformed
        Interfaz_Consulta.setVisible(true);
        ConsultaProductora2.hide();
    }//GEN-LAST:event_btnBack5ActionPerformed

    private void btnPeliculaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPeliculaActionPerformed
        CRUDPelicula.setVisible(true);
        InterfazCRUD.hide();
    }//GEN-LAST:event_btnPeliculaActionPerformed

    private void btnProductoraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProductoraActionPerformed
        CRUDProductora.setVisible(true);
        InterfazCRUD.hide();
    }//GEN-LAST:event_btnProductoraActionPerformed

    private void btnCreateProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateProdActionPerformed
        int año = Integer.parseInt(txtAñoProd.getText());
        consulta.insertarProductora(txtID.getText(), txtNombreProd.getText(), año, txtWWW.getText());
        JFrame frame = new JFrame();
        JOptionPane.showMessageDialog(frame,"Productora insertada con exito");
    }//GEN-LAST:event_btnCreateProdActionPerformed

    private void btnReadProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReadProdActionPerformed
        txtResultadoProd.setText(consulta.readProductora());
    }//GEN-LAST:event_btnReadProdActionPerformed

    private void btnUpdateProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateProdActionPerformed
        int año = Integer.parseInt(txtAñoProd.getText());
        consulta.updateProductora(txtID.getText(), txtNombreProd.getText(), año, txtWWW.getText());
        JFrame frame = new JFrame();
        JOptionPane.showMessageDialog(frame,"Productora actualizada con exito");
    }//GEN-LAST:event_btnUpdateProdActionPerformed

    private void btnDeleteProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteProdActionPerformed
        consulta.deleteProductora(txtID.getText());
        JFrame frame = new JFrame();
        JOptionPane.showMessageDialog(frame,"Productora eliminada con exito");
    }//GEN-LAST:event_btnDeleteProdActionPerformed

    private void btnBackCRUDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackCRUDActionPerformed
        InterfazCRUD.setVisible(true);
        CRUDProductora.hide();
    }//GEN-LAST:event_btnBackCRUDActionPerformed

    private void btnCreatePeliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreatePeliActionPerformed
        //id, nombre, genero, director, franquicia, pais de produccion, año de estreno, duracion, productora, actores
        int año = Integer.parseInt(txtAñoPeli.getText());
        int duracion = Integer.parseInt(txtDuracionPeli.getText());
        consulta.insertPelicula(txtIDPeli.getText(), txtNombrePeli.getText(), txtGeneroPeli.getText(), txtDirectorPeli.getText(), 
                txtFranquiciaPeli.getText(), txtPaisPeli.getText(), año, duracion, txtProductoraPeli.getText(), txtActor1.getText(), txtActor2.getText(), txtActor3.getText());
        JFrame frame = new JFrame();
        JOptionPane.showMessageDialog(frame,"Pelicula insertada con exito");
    }//GEN-LAST:event_btnCreatePeliActionPerformed

    private void btnReadPeliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReadPeliActionPerformed
        txtResultadoPeli.setText(consulta.readPelicula());
    }//GEN-LAST:event_btnReadPeliActionPerformed

    private void btnUpdatePeliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdatePeliActionPerformed
        int año = Integer.parseInt(txtAñoPeli.getText());
        int duracion = Integer.parseInt(txtDuracionPeli.getText());
        consulta.updatePelicula(txtIDPeli.getText(), txtNombrePeli.getText(), txtGeneroPeli.getText(), txtDirectorPeli.getText(), 
                txtFranquiciaPeli.getText(), txtPaisPeli.getText(), año, duracion, txtProductoraPeli.getText(), txtActor1.getText(), txtActor2.getText(), txtActor3.getText());
        JFrame frame = new JFrame();
        JOptionPane.showMessageDialog(frame,"Pelicula actualizada con exito");
    }//GEN-LAST:event_btnUpdatePeliActionPerformed

    private void btnDeletePeliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeletePeliActionPerformed
        consulta.deletePelicula(txtIDPeli.getText());
        JFrame frame = new JFrame();
        JOptionPane.showMessageDialog(frame,"Pelicula eliminada con exito");
    }//GEN-LAST:event_btnDeletePeliActionPerformed

    private void btnBackCRUD2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackCRUD2ActionPerformed
        InterfazCRUD.setVisible(true);
        CRUDPelicula.hide();
    }//GEN-LAST:event_btnBackCRUD2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interfaz_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interfaz_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interfaz_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interfaz_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interfaz_Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFrame CRUDPelicula;
    private javax.swing.JFrame CRUDProductora;
    private javax.swing.JFrame ConsultaPorFranquicia;
    private javax.swing.JFrame ConsultaPorRango;
    private javax.swing.JFrame ConsultaPorTitulo;
    private javax.swing.JFrame ConsultaProductora1;
    private javax.swing.JFrame ConsultaProductora2;
    private javax.swing.JFrame InterfazCRUD;
    private javax.swing.JFrame Interfaz_Consulta;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnBack1;
    private javax.swing.JButton btnBack2;
    private javax.swing.JButton btnBack3;
    private javax.swing.JButton btnBack4;
    private javax.swing.JButton btnBack5;
    private javax.swing.JButton btnBackCRUD;
    private javax.swing.JButton btnBackCRUD2;
    private javax.swing.JButton btnCRUD;
    private javax.swing.JButton btnConsulta;
    private javax.swing.JButton btnConsulta1;
    private javax.swing.JButton btnConsulta2;
    private javax.swing.JButton btnConsulta3;
    private javax.swing.JButton btnConsultar;
    private javax.swing.JButton btnConsultas;
    private javax.swing.JButton btnCreatePeli;
    private javax.swing.JButton btnCreateProd;
    private javax.swing.JButton btnDeletePeli;
    private javax.swing.JButton btnDeleteProd;
    private javax.swing.JButton btnPelicula;
    private javax.swing.JButton btnProductora;
    private javax.swing.JButton btnReadPeli;
    private javax.swing.JButton btnReadProd;
    private javax.swing.JButton btnUpdatePeli;
    private javax.swing.JButton btnUpdateProd;
    private javax.swing.JButton consFranquicia;
    private javax.swing.JButton consProd1;
    private javax.swing.JButton consProd2;
    private javax.swing.JButton consRango;
    private javax.swing.JButton consTitulo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JTextField txtActor1;
    private javax.swing.JTextField txtActor2;
    private javax.swing.JTextField txtActor3;
    private javax.swing.JTextField txtAño1;
    private javax.swing.JTextField txtAño2;
    private javax.swing.JTextField txtAñoPeli;
    private javax.swing.JTextField txtAñoProd;
    private javax.swing.JTextPane txtConsulta;
    private javax.swing.JTextPane txtConsulta1;
    private javax.swing.JTextPane txtConsulta2;
    private javax.swing.JTextPane txtConsulta3;
    private javax.swing.JTextPane txtConsulta4;
    private javax.swing.JTextField txtDirectorPeli;
    private javax.swing.JTextField txtDuracionPeli;
    private javax.swing.JTextField txtFranquicia;
    private javax.swing.JTextField txtFranquiciaPeli;
    private javax.swing.JTextField txtGeneroPeli;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtIDPeli;
    private javax.swing.JTextField txtNombrePeli;
    private javax.swing.JTextField txtNombreProd;
    private javax.swing.JTextField txtPaisPeli;
    private javax.swing.JTextField txtProductora;
    private javax.swing.JTextField txtProductora1;
    private javax.swing.JTextField txtProductoraPeli;
    private javax.swing.JTextPane txtResultadoPeli;
    private javax.swing.JTextPane txtResultadoProd;
    private javax.swing.JTextField txtTitulo;
    private javax.swing.JTextField txtWWW;
    // End of variables declaration//GEN-END:variables
}
